name: Validate and build

on:
  push:
    paths:
      - 'sdk/**/*.xml'
      - clonk.xsl
      - '**/*.css'
      - '**/*.js'
      - '**/*.py'
      - '**/*.pl'
      - 'Makefile'
      - 'images/**'
      - '*.po'
  pull_request:
    types: [ ready_for_review ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup saxonb-xslt, python, gettext
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext -y

      - name: Build docs
        run: |
          make -j$(nproc)

      - name: "Collect artifacts"
        run: |
          mkdir output
          mv online output
          mv chm output
          mv sdk-en output
          mv sdk output
          mv doku.pot output
          mv en.mo output
          mv Functions.txt output
          cd output
          zip -q -0 -r ../generated-docs.zip *

      - name: "Publish zipped Main Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs-nested-zip
          path: generated-docs.zip
