name: Validate and build

on:
  push

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libxml2-utils
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install libxml2-utils

      - name: Lint all XML files
        run: |
          xmllint --schema ./clonk.xsd --noout $(find sdk -name '.*' -prune -o -name \*.xml -print)

      - name: i18n Coverage
        uses: alexkiro/i18n-coverage@v1.0.1
        with:
          translations-path: './*.po'
          min-coverage: 100


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup saxonb-xslt, python, gettext
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext -y

      - name: Build docs
        run: |
          make -j$(nproc)

      - name: "Collect artifacts"
        run: |
          mkdir output
          mv online output
          mv chm output
          mv sdk-en output
          mv sdk output
          mv doku.pot output
          mv en.mo output
          mv Functions.txt output
          cd output
          zip -q -0 -r ../generated-docs.zip *

      - name: "Publish zipped Main Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs-nested-zip
          path: generated-docs.zip
