name: HTML-Preview

on:
  pull_request:
    types: [ ready_for_review ]

defaults:
  run:
    shell: bash

jobs:
  screenshot:
    name: Take screenshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup saxonb-xslt, python, gettext
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext -y

      - name: Build html docs
        run: |
          make -j$(nproc)


      - id: files
        name: Get changed xml files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'json'
          # Filter files using a glob filter
          filter: 'sdk/**/*.xml'

      - id: filelist
        name: Build list with changed html files
        run: |
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for file in ${files[@]}; do
            htmlfile=$(echo "${file}" | sed 's/sdk/online\/de\/sdk/; s/.xml/.html/')
            echo "Adding ${htmlfile}"
            htmlfiles="${htmlfiles}${htmlfile}, " 
          done
          htmlfiles=${htmlfiles::-2}
          echo $htmlfiles
          # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
          # echo "::set-output name=htmlfiles::${htmlfiles}"
          echo "htmlfiles=${htmlfiles}" >> $GITHUB_OUTPUT

      # Run Screenshot Comment Action
      - name: Take screenshots of changed html files and add to pull request
        uses: saadmk11/comment-webpage-screenshot@v0.5
        with:
          upload_to: github_branch
          # Capture Screenshots of Changed HTML Files
          capture_changed_html_files: no
          # Comma seperated paths to any other HTML File
          capture_html_file_paths: "${{ steps.filelist.outputs.htmlfiles }}"
