name: PR-Screenshot

on:
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup saxonb-xslt, python, gettext
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends libsaxonb-java python-libxml2 gettext -y

      - name: Build docs
        run: |
          make -j$(nproc)

      - name: "Collect artifacts"
        run: |
          mkdir output
          mv online output
          mv chm output
          mv sdk-en output
          mv sdk output
          mv doku.pot output
          mv en.mo output
          mv Functions.txt output
          cd output
          zip -q -0 -r ../generated-docs.zip *

      - name: "Publish zipped Main Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs-nested-zip
          path: generated-docs.zip

  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'json'
          # Filter files using a glob filter
          filter: 'sdk/**/*.xml'
      - run: |
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for file in ${files[@]}; do
          htmlfile=$(echo "${file}" | sed 's/sdk/online\/de\/sdk/; s/.xml/.html/')
          echo "Adding ${htmlfile}"
          htmlfiles="${htmlfiles}${htmlfile}, " 
          done
          htmlfiles=${htmlfiles::-2}
          echo $htmlfiles
